### PR TITLE
add image rotation option

### PR DESCRIPTION
**Pull request by SvePu**

### CODE REVIEW

**Comment by SvePu** [comment]
#33

**Comment by Eldenroot** [comment]
Thank you!

Anything else under the hood which we could implement/fix in 1.2.0 release?

**Comment by SvePu** [comment]
not atm  .... please check it before release

**Comment by Eldenroot** [comment]
I would like to try - I had been testing the version from yesterday - so without latest 2 PRs from you from today evening. So I will focus on them.

**Pull request merged**
