### PR TITLE
Fixes error (errorHandle -> error)

### PR DESCRIPTION
**Pull request by Eldenroot**
https://community.mybb.com/thread-219143-post-1336257.html#pid1336257

### CODE REVIEW

**Comment by Eldenroot** [comment]
#61

**Comment by Eldenroot** [comment]
@WildcardSearch please can you check this fix?

**Comment by WildcardSearch** [comment]
I'll try to look at it, tonight, @Eldenroot.

**Comment by Eldenroot** [comment]
@WildcardSearch - hi, do you have some free time to complete this? Thank you!

**Comment by WildcardSearch** [comment]
I'm struggling to find free time, right now.

**Comment by Eldenroot** [comment]
@lairdshaw - please, can you review to merge this? Thx

**Comment by lairdshaw** [comment]
@Eldenroot, this looks like it will fix the problem. The problem seems to be that this hook is called not just when rendering posts, but also when rendering private messages (or other content), in which case the `$post` global will not (or might not) even be set.

So, before merging this PR, let's ask: do we want this plugin to support private messages too?

**Comment by Eldenroot** [comment]
We should keep support for PM, because css class for autoresizing images is applied for img tags here as well.

**Comment by lairdshaw** [comment]
You mean add support for PM rather than keep, I think? It doesn't seem that the plugin currently supports PMs? Or is it intended to?

**Comment by Eldenroot** [comment]
Nope, right now we support only posts in threads... maybe it is enough, because there are no attachments in PMs supported. Maybe some useers send images in PMs in img tag (external URL) but it is a minority, so it is not something what must be added ASAP. Maybe some day be ready for better PM system in MyBB which will have full support for attachments (like phpBB has).

**Comment by lairdshaw** [comment]
In that case, I would suggest an alternative to this PR. Rather than setting `$post['pid']` towards the end of the function if it is not already set, check up the top for the existence of the global `$post` variable, and if it is empty, then simply return `$message`. Something like this (just below the declaration of the globals):

```php
if (empty($post)) return $message;
```

**Comment by Eldenroot** [comment]
I would like to add a simple support for 3rd party plugins which enhance PMs in MyBB .) so everyone can easily use this in PMs.

Please, could you one day (if not, it is ok, not a priority) open a PR with your idea wrote above? I would be really grateful! Thx!

**Comment by lairdshaw** [comment]
Done in pull #70.

**Comment by Eldenroot** [comment]
Rejected.

**Pull request closed without merging**
